adding atom commands

diff --git a/bin/atom b/bin/atom
--- a/bin/atom
+++ b/bin/atom
@@ -3,8 +3,29 @@ VERSION="0.8.0"
 INSTALL_PREFIX=
 CONFIG_DIR="$PREFIX/etc/atom"
 PKG=`which pkg`
-ATOM="$PKG -C $HOME/.atom/pkg.conf"
+ATOM_HOME="$HOME/.atom"
+ATOM="$PKG -C $ATOM_HOME/pkg.conf"
+MANIFEST_YAML=manifest.yaml
 export INSTALL_AS_USER=1
+
+ANDROID_API=21
+ARCH=arm
+PLATFORM=generic
+TOOLCHAIN=TODO
+HOST_OS=`uname -s`
+HOST_OS_LOWER=`echo $HOST_OS |  tr '[:upper:]' '[:lower:]'`
+
+UNZIP=`which unzip`
+NDK_URL="https://dl.google.com/android/repository/android-ndk-r16b-$HOST_OS_LOWER-x86_64.zip"
+NDK_ZIP="android-ndk-r16b-$HOST_OS_LOWER-x86_64.zip"
+NDK_DIR="android-ndk-r16b"
+ANDROID_NDK_PATH=
+TOOLCHAIN_HOME=$ATOM_HOME/toolchains/android-$ANDROID_API/$ARCH/
+
+ADB=`which adb`
+ANDROID_SERIAL=
+STAGING_DIR="$ATOM_HOME/staging/android$ANDROID_API-$ARCH-$PLATFORM"
+DEVICE_DESTINATION=/vendor
 
 PKG_PRE_ARGS=
 PKG_CMD=
@@ -12,10 +33,17 @@ DEBUG=0
 ATOM_CMD=
 POST_ARGS=
 
+# XXX DEBUG STUFF - REMOVE
+# ATOM_HOME="/tmp/$HOME/.atom"
+DEVICE_DESTINATION="/data/local/tmp"
+# CONFIG_DIR="/Users/apowers/Projects/atom/default-config"
+
 # this is the starting point, called on the very last line of this file
 main () {
     debug "atom version v$VERSION"
     debug " "
+
+    atom_cmd_init
 
     scan_args "$@"
     print_configuration
@@ -26,6 +54,7 @@ main () {
     fi
 
     # TODO: if the PKG_CMD is "help" it should show some help for 'atom' and 'pkg'
+    # TODO: atom_check_init || atom_init
 
     if [ "$ATOM_CMD" != "" ]; then
         run_atom_cmd
@@ -33,6 +62,13 @@ main () {
     fi
 
     run_pkg_cmd
+}
+
+run_pkg_cmd() {
+    debug "pkg command: $ATOM $ARGS"
+    # basically calls 'pkg' with the right configuration file
+    # and all the rest of the args that were specified on the command line
+    $ATOM $PKG_PRE_ARGS $PKG_CMD $POST_ARGS
 }
 
 # parse the command line arguments
@@ -43,11 +79,9 @@ scan_args() {
         value=$2
         shift
 
-        echo "ARG: $arg"
         # after a command is found, just push everything on to the post args list
         if [ "$PKG_CMD" != "" ] || [ "$ATOM_CMD" != "" ]; then
             POST_ARGS="$POST_ARGS $arg"
-            echo "pushed arg \"$arg\", continuing"
             continue
         fi
 
@@ -71,7 +105,7 @@ scan_args() {
             add|alias|annotate|audit|autoremove|backup|check|clean|config|create|delete|fetch|help|info|install|lock|plugins|query|register|remove|repo|rquery|search|set|ssh|shell|shlib|stats|unlock|update|updating|upgrade|version|which)
                 PKG_CMD=$arg ;;
             # atom commands
-            init|push|create-template)
+            init|push|create-template|create-package)
                 ATOM_CMD=$arg ;;
 
             *)
@@ -117,6 +151,26 @@ print_usage() {
     exit 0
 }
 
+# our generic "print help then quit" function
+print_push_help() {
+    echo
+    echo "atom push [android_serial]"
+    echo
+    echo "environment variables:"
+    echo "$ANDROID_SERIAL   if set, the second argument 'android_serial' may be omitted"
+    echo
+    echo "Pushes all the installed files to the device specified by <android_serial>."
+    echo "    <android_serial> must be the valid serial of a device for 'adb push'."
+    echo "        If you don't know your device serial, type 'adb devices' and its the thing"
+    echo "        at the beginning of the line. For example:"
+    echo "            List of devices attached"
+    echo "            10.100.100.150:5555     device"
+    echo "            04157df435240637        device"
+    echo
+    echo "            ^^^^^^^^^^^^^^^^^^^^--- this is your device serial"
+    echo
+}
+
 # if debugging is turned on (-d flag), print configuration information
 print_configuration() {
     debug "pkg: $PKG"
@@ -129,29 +183,237 @@ print_configuration() {
 # parse pkg commands to be smart about which to ignore
 run_atom_cmd() {
     case $ATOM_CMD in
-        init) atom_cmd_init ;;
-        push) atom_cmd_push ;;
-        create-template) atom_cmd_template ;;
+        init) atom_cmd_init $POST_ARGS;;
+        push) atom_cmd_push $POST_ARGS;;
+        create-template) atom_cmd_template $POST_ARGS;;
+        create-package) atom_cmd_create_pkg $POST_ARGS;;
     esac
     exit 0
 }
 
 atom_cmd_init() {
-    die "INIT NOT IMPLEMENTED YET"
+    if [ -d $ATOM_HOME ]; then
+        echo "atom home directory exists at: $ATOM_HOME"
+        return 0
+    fi
+
+    echo "atom init running ..."
+    mkdir -p $ATOM_HOME
+    cp -a $CONFIG_DIR/ $ATOM_HOME
+
+    SED_HOME=`echo $HOME | sed 's/\\//\\\\\\//g'`
+    sed "s/\$HOME/$SED_HOME/g" $CONFIG_DIR/pkg.conf > $ATOM_HOME/pkg.conf
+    echo "Created atom home directory: $ATOM_HOME"
 }
 
 atom_cmd_push() {
-    die "PUSH NOT IMPLEMENTED YET"
+    #################################
+    # Push Configuration
+    #################################
+
+    # make sure we have adb installed
+    check_adb
+
+    # if the user requested help, do it
+    if [ x$1 == "x--help" ] || [ x$1 == "x-h" ]; then
+        print_push_help
+        exit 0
+    fi
+
+    if [ ! -d $STAGING_DIR ]; then
+        echo
+        echo "ERROR: the staging directory '$STAGING_DIR' is missing or not a valid directory."
+        print_push_help
+        exit 1
+    fi
+
+    # if the second argument is set, use that for ANDROID_SERIAL
+    if [ "$1" != "" ]; then
+        ANDROID_SERIAL=$1
+    fi
+
+    # if ANDROID_SERIAL isn't set (either by the environment variable or the command line) then quit
+    if [ "$ANDROID_SERIAL" == "" ]; then
+        echo
+        echo "ERROR: <android_serial> not specified."
+        print_push_help
+        exit 1
+    fi
+
+    ADB_CMD="$ADB -s $ANDROID_SERIAL"
+    # show configuration
+    debug " "
+    debug "Push Configuration:"
+    debug "ADB:              $ADB"
+    debug "STAGING_DIR:      $STAGING_DIR"
+    debug "ANDROID_SERIAL:   $ANDROID_SERIAL"
+    debug "ADB COMMAND:      $ADB_CMD"
+    debug " "
+
+    #################################
+    # Push Connect to device
+    #################################
+    adb_connect
+
+    # make sure device is ready
+    STATE=`$ADB_CMD get-state`
+    if [ x$STATE != xdevice ]; then
+        echo
+        echo "ERROR: device $ANDROID_SERIAL is not ready"
+        echo
+        exit 1
+    fi
+
+    echo "device '$ANDROID_SERIAL' is ready ..."
+
+    # prepare filesystem for writing
+    # XXX: adb always returns 0 from these commands, so it's impossible to tell if they worked or not
+    $ADB_CMD root
+    adb_connect
+    $ADB_CMD remount
+
+    #################################
+    # Push Files
+    #################################
+
+    # log files that were written
+    # find inst-test -type f > $ATOM_LOG
+
+    $ADB_CMD push $STAGING_DIR/* $DEVICE_DESTINATION
+    if [ $? -ne 0 ]; then
+        echo
+        echo "ERROR: could not push files to device."
+        echo "ERROR: installation failed."
+        echo
+    else
+        echo
+        echo "Install succeded! Done."
+        echo
+    fi
+}
+
+adb_connect() {
+    # check to see if the serial matches an IP / port like: x.x.x.x:yyyy
+    if [[ $ANDROID_SERIAL =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}(:[0-9]{1,5})?$ ]]; then
+        $ADB connect $ANDROID_SERIAL
+    fi
 }
 
 atom_cmd_template() {
-    die "CREATE-TEMPLATE NOT IMPLEMENTED YET"
+
+cat << EOF > $MANIFEST_YAML
+name: dummy-pkg
+version: 0.1.0
+origin: test/dummy-pkg
+comment: This is just a test
+arch: android:21:arm:32
+abi: Android:21:arm
+www: http://ato.ms
+maintainer: donut@emailme.com
+prefix: examples
+licenselogic: single
+licenses: [MIT]
+desc: <<EOD
+This is the description of the file.
+It is really good.
+
+I mean its just a test. But a good
+test. You know what I'm sayin?
+EOD
+options: {
+  MACHINE: armv7,
+  ARCH: arm,
+  SYSTEM: android,
+  ANDROID-API: "21",
+  CROSS_COMPILE: arm-linux-androideabi
+}
+categories: [blah, ugh, grunt]
+files: {
+  examples/dummy-pkg/foo: -,
+  examples/dummy-pkg/README.md: -,
+}
+EOF
+
 }
 
-run_pkg_cmd() {
-    debug "pkg command: $ATOM $ARGS"
-    $ATOM $PKG_PRE_ARGS $PKG_CMD $POST_ARGS
+find_android_ndk() {
+    # TODO check ANDROID_NDK_PATH variable
+    # TODO check known locations (~/Library/... on Darwin)
+    return 1
 }
+
+install_android_ndk() {
+    echo "Android Native Development Kit (NDK) not found. Installing ... "
+    TMP_DIR=`mktemp -d`
+    CWD=`pwd`
+
+    check_prog_dependency wget
+    check_prog_dependency unzip
+    WGET=`which wget`
+    UNZIP=`which unzip`
+
+    debug "wget installed: $WGET"
+    debug "unzip installed: $UNZIP"
+
+    cd $TMP_DIR
+    $WGET $NDK_URL
+    $UNZIP $NDK_ZIP
+    ANDROID_NDK_PATH=$TMP_DIR/$NDK_DIR
+    cd $CWD
+}
+
+create_toolchain() {
+    if [ -d $TOOLCHAIN_HOME ]; then
+        return 0;
+    fi
+
+    find_android_ndk
+    if [ $? -eq 1 ]; then
+        install_android_ndk
+    fi
+
+    debug "Android NDK: $ANDROID_NDK_PATH"
+    MKTOOLCHAIN="$ANDROID_NDK_PATH/build/tools/make-standalone-toolchain.sh"
+    if [ ! -x $MKTOOLCHAIN ]; then
+        die "Internal error: Android NDK installed but 'make-standalone-toolchain.sh' not found."
+    fi
+
+    $MKTOOLCHAIN --arch=$ARCH --platform=android-$ANDROID_API --install-dir=$TOOLCHAIN_HOME --stl=libc++
+}
+
+atom_cmd_create_pkg() {
+    create_toolchain
+}
+
+check_prog_dependency() {
+    PROG=$1
+    PROG_PATH=`which $PROG`
+    if [ $? -eq 1 ]; then
+        echo
+        echo "Could not find the required program '$PROG' on your system."
+        echo "Please install it and try again."
+        echo
+        exit 1
+    fi
+}
+
+check_adb() {
+    ADB=`which adb`
+    if [ $? -eq 1 ]; then
+        echo
+        echo "ERROR: 'which adb' could not find adb."
+        echo
+        echo "Please install ADB and / or make sure it is on your path."
+        echo "You can download Android Platform Tools (which contains ADB) here:"
+        echo "    https://developer.android.com/studio/releases/platform-tools.html#download"
+        echo
+        echo "Your path is currently:"
+        echo "    $PATH"
+        echo
+        exit 1
+    fi
+}
+
 
 die() {
     ERRMSG=$1
